include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-fakesip
PKG_RELEASE:=4

LUCI_TITLE:=LuCI support for FakeSIP
LUCI_DEPENDS:=+fakesip
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
